export default function TermsAndConditionsComponent() {
  return (
    <section className="flex justify-center">
      <div className="max-w-3xl mx-auto mx-4 sm:mx-0 px-4 pt-6 lg:pt-10 pb-12 sm:px-6 lg:px-8 border rounded-xl border bg-card shadow mt-14 mb-10 bg-white">
        <div className="max-w-2xl">
          <div className="space-y-5 md:space-y-6">
            <div className="space-y-3">
              <h1 className="text-2xl font-bold md:text-3xl dark:text-white">
                Terms and Conditions
              </h1>
            </div>
            <ul className="list-disc">
              <li>
                <span className="font-semibold">Acceptance of Terms: </span>
                By using our website tools, you agree to abide by the terms and
                conditions outlined herein.
              </li>
              <li className="mt-4">
                <span className="font-bold">Use of Tools: </span>
                You must provide accurate and complete information when using
                the UPI tool. The website is not responsible for any
                inaccuracies or errors resulting from incomplete or incorrect
                information provided by users.
              </li>
              <li className="mt-4">
                <span className="font-bold">Limitation of Liability: </span>
                The website owner shall not be liable for any direct, indirect,
                incidental, special, or consequential damages arising out of the
                use or inability to use the tools. The website owner does not
                guarantee the accuracy, completeness, or timeliness of the UPI
                links generated by the tool.
              </li>
              <li className="mt-4">
                <span className="font-bold">Privacy Policy: </span>
                The use of the tools is subject to the website's Privacy Policy,
                which can be found <a href="/privacy-policy">here</a>.
              </li>
              <li className="mt-4">
                <span className="font-bold">Changes to Terms: </span>
                The website owner reserves the right to update or modify these
                terms and conditions at any time without prior notice. Users are
                encouraged to review the terms periodically for changes.
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
}
