export const countries = [
  { name: 'India', code: '+91' },
  { code: '+1', name: 'US' },
  { code: '+93', name: 'Afganistan' },
  { code: '+213', name: 'Algeria' },
  { code: '+54', name: 'Argentina' },
  { code: '+61', name: 'Australia' },
  { code: '+880', name: 'Bangladesh' },
  { code: '+1', name: 'Canada' },
  { code: '+86', name: 'China' },
  { code: '+45', name: 'Denmark ' },
  { code: '+20', name: 'Egypt' },
  { code: '+251', name: 'Ethiopia' },
  { code: '+33', name: 'France ' },
  { code: '+49', name: 'Germany ' },
  { code: '+62', name: 'Indonesia ' },
  { code: '+98', name: 'Iran' },
  { code: '+39', name: 'Italy' },
  { code: '+254', name: 'Kenya' },
  { code: '+60', name: 'Malaysia' },
  { code: '+52', name: 'Mexico' },
  { code: '+382', name: 'Montenegro' },
  { code: '+977', name: 'Nepal ' },
  { code: '+31', name: 'Netherlands ' },
  { code: '+64', name: 'New Zealand ' },
  { code: '+92', name: 'Pakistan ' },
  { code: '+63', name: 'Philippines ' },
  { code: '+7', name: 'Russia ' },
  { code: '+966', name: 'Saudi Arabia ' },
  { code: '+65', name: 'Singapore ' },
  { code: '+27', name: 'South Africa ' },
  { code: '+34', name: 'Spain ' },
  { code: '+94', name: ' Sri Lanka ' },
  { code: '+66', name: 'Thailand ' },
  { code: '+90', name: 'Turkey ' },
  { code: '+971', name: 'United Arab Emirates' },
  { code: '+44', name: 'United Kingdom ' },
  { code: '+84', name: 'Vietnam ' },
];
